### ISSUE TITLE
Modelado para Stock

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#1]
Diseñar el modelado de la base de datos del modulo de stock según las directrices dictadas en clase de Sistemas de Gestión.

**Comment by ahalaburda** [comment]
Según la ultima evaluación del Profesor Samaniego, se cambiaron algunos campos nada mas y el modelado de stock ya estaría finalizado. Se aguarda la aprobación

**Comment by willymarpuk** [comment]
Tras la ultima modificación, no hubo mas sugerencias para volver a modificar este modelado.
