### ISSUE TITLE
Modelado para Caja y Bancos

### ISSUE THREAD

**Issue by willymarpuk** [ahalaburda/gestion#10]
Diseñar el modelado de la base de datos del modulo de Caja y Bancos según las directrices dictadas en clase de Sistemas de Gestión.

**Comment by ahalaburda** [comment]
Se realizaron segun las recomendaciones del profesor cambios.
Se borro la tabla caja detalles.

**Comment by ahalaburda** [comment]
Faltaria agregar a la tabla bancos sucursal y correo de contacto

**Comment by willymarpuk** [comment]
falta tabla de parametros

**Comment by ahalaburda** [comment]
falta agregar la tabla apertura_caja y borrar los campos de persona, saldos, fecha de apertura y cierre  de la tabla cajas

**Comment by willymarpuk** [comment]
Se agrego la tabla de parametros, auditoria, y se borro los campos de persona, saldos, fecha de apertura y cierre de la tabla cajas y se creo la tabla apertura_caja con dichos campos citados anteriormente.
Se agrego los campos de correo y sucursal en la tabla bancos

**Comment by willymarpuk** [comment]
Se agrego al modelo de datos las tablas para realizar asientos automaticos

**Comment by ahalaburda** [comment]
Faltantes

- borrar la columna de descripcion en las tablas de detalles

- agregar la columna total a la cabecera de las  tablas con detalles

**Comment by willymarpuk** [comment]
Se borro la columna descripcion en las tablas de detalles y se agrego la columna total a la cabecera de las tablas con detalles.

**Comment by willymarpuk** [comment]
Falta agregar la tabla user  y roles al modelo de datos.

**Comment by willymarpuk** [comment]
Se agrego la tabla users al modelo de datos

**Comment by willymarpuk** [comment]
Falta agregar el campo apertura_id en movimientos de cajas.

**Comment by willymarpuk** [comment]
Se agrego el campo apertura_id en movimientos de cajas, el campo estado_id en cheques_entrantes y cheques_propios y el campo persona_id en la tabla users.
