### ISSUE TITLE
Crear ABM para caja

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#15]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by ahalaburda** [comment]
Se genero con la herramienta scaffold de ruby on rails la ruta, controladores vistas y modelos del abm de caja

**Comment by ahalaburda** [comment]
FALTANTES:
*-Validación del lado del Cliente
*-Validación del lado del Servidor.
*-Edición de registro en el abm principal para actualización de dato.
*-Ordenamiento por columnas.
*-Búsqueda.
*-Paginacion.
*-Búsqueda Filtrada.
*-Reportes.

**Comment by willymarpuk** [comment]
Se agrego la funcionalidad de reportes, edicion de registro en el abm principal para actualizacion de dato, busqueda, paginacion y ordenamiento por columna para este abm.

FALTANTES:
*-Validación del lado del Cliente
*-Validación del lado del Servidor.
*-Búsqueda Filtrada.

**Comment by ahalaburda** [comment]
Se agregaron validaciones del lado del cliente y del servidor

**Comment by ahalaburda** [comment]
Se agrego los modals que faltaban anteriormente de estados y personas. 
FALTANTES:
-Búsqueda Filtrada.

**Comment by ahalaburda** [comment]
se agrego una tabla de apertura de caja para realizar correctamente la apertura, y caja sea un abm simple, dando la posibilidad a futuro a la empresa poder incrementar su numero de cajas
