### ISSUE TITLE
Crear ABM para Movimientos de Bancos

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#16]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
Se creo el abm de boletas de depositos con su respectiva validacion lado cliente y servidor. Falta la funcionalidad de reportes y mejorar la interfaz. Con respecto a su detalle, tenemos problemas con la cantidad de campos que debe tener este detalle

**Comment by willymarpuk** [comment]
Se esta mejorando las vistas de este abm y su detalle

**Comment by willymarpuk** [comment]
Se envio un correo a la profesora Mirta para recibir asesoria acerca del problema presentado

**Comment by willymarpuk** [comment]
Falta agregar un campo "Fecha" a la cabecera de movimientos de cajas con una migracion y actualizar el modelo de datos de caja y bancos.

**Comment by willymarpuk** [comment]
Se soluciono el problema con los detalles de boletas de depositos, falta mejorar su interfaz

**Comment by willymarpuk** [comment]
Se agrego mediante una migracion el campo "fecha" faltante pero falta agregar(actualizar) este campo al modelado de datos, y se mejoro la interfaz de este abm.

**Comment by willymarpuk** [comment]
Se agrego el campo "Fecha", faltante en el modelo de datos

**Comment by willymarpuk** [comment]
Se esta mejorando la interfaz, falta la funcionalidad de reportes

**Comment by willymarpuk** [comment]
Se agrego el campo total al abm

**Comment by willymarpuk** [comment]
falta agregar la funcionalidad de callbacks para calculo automatico de saldos

**Comment by ahalaburda** [comment]
Faltantes 
- modals de tipo de movimientos,bancos y cuentas bancarias
- la funcionalidad de callbacks para calculo automático de saldos

**Comment by ahalaburda** [comment]
Se realizo las funcionalidades para calculos de saldos y los reportes no son necesarios ya que se reflejan en el libro de banco
