### ISSUE TITLE
Crear ABM para Personas

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#17]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
Se creo el abm de personas, pero aun falta agregar la funcionalidad de reportes al mismo, como tambien mejorar su interfaz

**Comment by willymarpuk** [comment]
Se agrego las funcionalidades de reportes para este abm

**Comment by willymarpuk** [comment]
Faltan los modals para este abm
