### ISSUE TITLE
Crear ABM para Cheques Propios

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#21]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
se creo el abm de cheques propios con su validacion del lado cliente y servidor, falta la funcionalidad de reportes para este abm.

**Comment by willymarpuk** [comment]
Se agrego la funcionalidad de reportes para el abm de cheques propios
