### ISSUE TITLE
Crear ABM para Boletas de depositos detalles

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#22]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
hay problemas en la creacion de los detalles de este abm, se esta utilizando formularios anidados para la realizacion del mismo.

**Comment by willymarpuk** [comment]
se soluciono de forma parcial el problema de la creacion de detalles de las boletas de depositos. Ahora el problema es sobre la cantidad de campos que debe tener este detalle.

**Comment by willymarpuk** [comment]
Hay problemas para renderizar el formulario de boletas de depositos detalles

**Comment by willymarpuk** [comment]
se esta mejorando las vistas del detalle

**Comment by willymarpuk** [comment]
Se envio un correo a la profesora Mirta para recibir asesoria acerca del problema presentado

**Comment by willymarpuk** [comment]
Se soluciono el problema con los detalles de boletas de depositos, falta mejorar su interfaz

**Comment by willymarpuk** [comment]
Falta agregar funcionalidad de reportes al detalle de boletas de depositos

**Comment by willymarpuk** [comment]
falta agregar funcionalida de callbacks para calculo de saldos

**Comment by ahalaburda** [comment]
se mejoro la ui, y se agregaron los calculos de saldos , funciones automaticas

faltantes

reportes

**Comment by willymarpuk** [comment]
Se agrego la validacion faltante, y los reportes se reflejan en el libro de banco
