### ISSUE TITLE
Crear ABM para Boletas de Depositos

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#23]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
Se creo el abm de boletas de depositos con su respectiva validacion lado cliente y servidor. Falta la funcionalidad de reportes y mejorar la interfaz.

**Comment by willymarpuk** [comment]
se mejoro la interfaz de boletas de depositos

**Comment by willymarpuk** [comment]
Se agrego la funcionalidad de reportes al abm.

**Comment by willymarpuk** [comment]
falta funcionalidad de Callbacks para el calculo de saldos

**Comment by ahalaburda** [comment]
La funcionalidad de calculos de saldo ya realizo y las validaciones ya fueron hechas
