### ISSUE TITLE
Crear ABM para Cheques Entrantes

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#24]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
Se creo este abm con sus validaciones lado cliente y servidor, le falta la funcionalidad de reportes y tambien mejorar su interfaz

**Comment by willymarpuk** [comment]
se agrego la funcionalidad de reportes, falta mejorar su interfaz

**Comment by willymarpuk** [comment]
Faltan los modals para este abm

**Comment by ahalaburda** [comment]
Problemas con el modal de bancos, no guarda y no cierra la ventana emergente

**Comment by ahalaburda** [comment]
se resolvio el problema, una funcion de javascript estaba con errores.
