### ISSUE TITLE
Crear ABM para Chequeras

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#25]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
se creo el abm de chequeras con su respectiva validacion del lado cliente y servidor, tambien se agrego la funcionalidad de reportes al mismo. Falta agregar los modals al campo que lo requieran y falta mejorar su interfaz.

**Comment by willymarpuk** [comment]
Se agregaron algunos campos faltantes para este abm.
