### ISSUE TITLE
Crear ABM para Movimientos de Cajas

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#26]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
Se creo el abm de movimientos de cajas con su respectiva validacion lado cliente y servidor. Falta la funcionalidad de reportes y mejorar la interfaz. Con respecto a su detalle, tenemos problemas con la cantidad de campos que debe tener este detalle

**Comment by willymarpuk** [comment]
Se esta mejorando la interfaz de este abm con su detalle

**Comment by willymarpuk** [comment]
Se envio un correo a la profesora Mirta para recibir asesoria acerca del problema presentado

**Comment by willymarpuk** [comment]
Falta agregar un campo "Fecha" a la cabecera de movimientos de cajas con una migracion y actualizar el modelo de datos de caja y bancos.

**Comment by willymarpuk** [comment]
Se soluciono el problema de los detalles de este abm, Se agrego mediante una migracion el campo "fecha" faltante pero falta agregar(actualizar) este campo al modelado de datos.

**Comment by willymarpuk** [comment]
Se agrego el campo "Fecha", faltante en el modelo de datos.

**Comment by willymarpuk** [comment]
Se mejoro la interfaz de este abm, falta agregar la funcionalidad de reportes.

**Comment by ahalaburda** [comment]
Se realizaron algunas mejoras en la interfaz según recomendaciones de la ing. Mirta Arambulo. Cambiando el tamaño de letras, botones. y se agrego la funcionalidad de minimizar y maximizar la cabecera.

**Comment by ahalaburda** [comment]
Faltantes:

- la cabecera de apertura de caja debe sumar o restar a medida que se ingresan valores de ingreso u egreso y setear el valor en saldo efectivo y o en saldo cheque

**Comment by ahalaburda** [comment]
al generar una apertura setea el valor agregado en los saldos iniciales. 
FALTANTES
- realizar las operaciones al agregarse un movimiento de caja

**Comment by ahalaburda** [comment]
FALTANTES
-realizar las operaciones  al agregarse un movimiento de caja
-eliminar el campo descripción del detalle
-cambiar el tipo de dato date a datetime o timestamp

**Comment by ahalaburda** [comment]
Se cambio el tipo de dato en movimientos de caja de la columna fecha, se elimino el campo descripción de movimientos de cajas detalles de la base de datos y también de los abms.

Faltantes
realizar las operaciones al agregarse un movimiento de caja

**Comment by ahalaburda** [comment]
filtrado en tabla de movimientos por caja
Faltantes
- modals para cheque propio y cheque entrante

- borrar el input de caja en movimientos de caja del abm y pasar por ajax

- realizar operacion de calculo de saldo actuales de cheque y efectivo

- realizar operacion de calculo en el campo total de movimientos de caja

- Reportes

**Comment by ahalaburda** [comment]
se agregaron los modals para cheque propio y cheque entrante
Faltantes

- filtrado en tabla de movimientos por caja

- borrar el input de caja en movimientos de caja del abm y pasar por ajax

- realizar operacion de calculo de saldo actuales de cheque y efectivo

- agregar el campo total a el abm

- realizar operación de calculo en el campo total de movimientos de caja

- Reportes

**Comment by ahalaburda** [comment]
se realizaron modificaciones en el abm para que muestre por defecto un formulario del detalle

**Comment by ahalaburda** [comment]
Ya se puede realizar las operaciones de calculo de saldo actuales de cheque y efectivo. Se agrego también el campo total a el abm y obtiene en tiempo real el monto total.

Faltantes

- filtrado en tabla de movimientos por caja

- borrar el input de caja en movimientos de caja del abm y pasar por ajax

- Reportes

- cierre de caja

**Comment by ahalaburda** [comment]
Se agrego el filtrado en tabla de movimientos por caja segun el id de la caja que se esta utilizando, 

Faltantes

- borrar el input de caja en movimientos de caja del abm y pasar por ajax

- Reportes

- cierre de caja

**Comment by ahalaburda** [comment]
se borro el input de caja y se pasa por segundo plano el valor de la caja para guardar.
También se agrego a los parámetros lo campos de montos totales y se les quito el disabled ya que no guarda los valores en la base de datos.

Se esta trabajando en los callbacks para realizar el calculo total de la caja y poder realizar el cierre de caja con esos valores.
Faltantes

- Reportes

- cierre de caja

**Comment by ahalaburda** [comment]
Se agrego funciones para realizar los calculos de monto en la caja y se realizo tambien el cierre de caja con eso valores
Tambien se realizaron algunas mejoras en la UI del abm 

Faltantes
-Reportes

**Comment by ahalaburda** [comment]
Los reportes no son necesarios ya que se refleja en el libro de caja.
