### ISSUE TITLE
Crear ABM para Tipos de  Movimientos

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#27]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
Se genero con la herramienta scaffold de ruby on rails la ruta, controladores vistas y modelos del abm de Tipos de Movimientos

**Comment by willymarpuk** [comment]
Hubo conflictos al realizar la unión a la rama principal y tuvimos que retroceder 2 commits

**Comment by willymarpuk** [comment]
ya se puede editar un campo de la grilla de datos in que se renderice a otra pagina.

**Comment by willymarpuk** [comment]
ya se puede realizar reportes en formato pdf y xls, logradas con las gemas thinreports y to_xls instaladas
