### ISSUE TITLE
Crear ABM para Bancos

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#28]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by ahalaburda** [comment]
Se genero con la herramienta scaffold de ruby on rails la ruta, controladores vistas y modelos del abm de Bancos

**Comment by ahalaburda** [comment]
Se tenia un problema en las rutas con unos de los componentes del framework de front end que ya se ha solucionado, faltaria aun las validaciones para cada campo del lado del servidor y del lado del cliente

**Comment by ahalaburda** [comment]
Las validaciones del lado del cliente como del servidor ya han funcionan, también se utilizo datatables para la ordenación, búsqueda y paginacion con la gema kaminari para la tabla de listado.
También se camino la ruta para que no redirija a otra vista a la hora de guardar, como así también en caso de que se quisiera editar algún registro los datos son mandados al formulario que se encuentra en la parte superior y no entra vista.

FALTANTES:
*-Traducción de la herramienta datatable al español
*-Mejora en la interfaz de datatable
-Búsqueda Filtrada.
-Reportes.

**Comment by ahalaburda** [comment]
Se paso a español la herramienta datatable y se hizo una pequeña mejora en la interfaz de esta.
-Mejora en la interfaz de datatable(en proceso)
-Búsqueda Filtrada.
-Reportes.

**Comment by ahalaburda** [comment]
Se agrego los botones para realizar los reportes, por el momento solo se puede imprimir el reporte, falta realizar para exportar a pdf y xls.

-Mejora en la interfaz de datatable(en proceso)
-Búsqueda Filtrada.
-Reportes. (falta PDF y XLS)

**Comment by willymarpuk** [comment]
agregue funcionalidad de reportes al abm, pero faltan agregar unos campos al abm que se realizara mediante una migracion

**Comment by ahalaburda** [comment]
Se agregaron los campos de Pais, departamento y cuidad. Para eso también se estuvo trabajando en los abms de cada campo faltante con sus respectivas relaciones.
También se realizaron los cambios necesarios en el controlador como también en la vista de bancos.

**Comment by ahalaburda** [comment]
Se realizaron algunas mejoras en el código.

-Falta agregar las referencias correctamente de los campos recientemente agregados para que se muestren sin errores en las vista de bancos. 
-Búsqueda Filtrada.

**Comment by ahalaburda** [comment]
luego de agregar modals para agregar una ciudad, departamento y/o pais, la edicion de un registro agregado no funciona, se esta debuggeando el codigo para saber cual es el problema

**Comment by ahalaburda** [comment]
Se agregaron las referencias de los campos ultimos agregados.
Se reparo el bug que no permitía editar un registro, el causante eran los modals por lo que se tuvieron que remover temporalmente. también se dejo de utilizar la gema simple form  por errores también que esta tenia por lo que se volvió a forma nativa de rails con form_for y se soluciono el problema que teníamos anteriormente. Dejando pendiente lo siguiente:
*- los campos que son requeridos necesita un identificador
*- mejorar la interfaz de mensajes de error de las validaciones
*- agregar modal para agregar nuevos campos si es necesario en un campo
-búsqueda filtrada

**Comment by ahalaburda** [comment]
Se agrego le plugin select2 para que el select tenga búsqueda con filtrada

- los campos que son requeridos necesita un identificador
- mejorar la interfaz de mensajes de error de las validaciones
- agregar modal para agregar nuevos campos si es necesario en un campo
-búsqueda filtrada

**Comment by ahalaburda** [comment]
Se agrego el identificador para campo requerido

**Comment by ahalaburda** [comment]
Se agrego los modals que faltaban anteriormente de estados y personas. 
faltante
* búsqueda filtrada

**Comment by ahalaburda** [comment]
se cierra el issue de bancos ya que cumple con todas las funciones de un ABM y se genera un issue como requisito no funcional de busqueda filtrada
