### ISSUE TITLE
Crear ABM para Cuentas Bancarias

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#29]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
se creo el abm de cuentas bancarias, con las validaciones del lado cliente y servidor, falta la funcionalidad de reportes y mejorar la interfaz

**Comment by willymarpuk** [comment]
se agrego la funcionalidad de reportes para este abm. Falta mejorar su interfaz.

**Comment by willymarpuk** [comment]
Faltan los modals para este abm
