### ISSUE TITLE
Crear ABM para Firmantes

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#30]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

**Comment by willymarpuk** [comment]
se creo el abm para firmantes, con su validacion del lado cliente y servidor, falta la funcionalidad de reporte y mejorar la interfaz

**Comment by willymarpuk** [comment]
se agrego la funcionalidad de reportes para este abm.

**Comment by willymarpuk** [comment]
Faltan los modals para este abm
