### ISSUE TITLE
Crear ABM Pais, Departamento y Ciudad

### ISSUE THREAD

**Issue by ahalaburda** [ahalaburda/gestion#48]
Realizar las vistas, modelos y controladores, siguiendo las convenciones de ruby on rails y con sus respectivas validaciones del lado del servidor como del lado del cliente.

Se deben generar los siguientes abm segun las sugerencias tomadas de los profesores, luego de la presentacion de los modelados.

**Comment by ahalaburda** [comment]
Se generaron las vistas, controladores, modelos y rutas para los abm de País, departamento y ciudades.

*- Falta reportes en PDF y XLS

**Comment by ahalaburda** [comment]
Se agregaron también sus respectivas validaciones para campo, como así también reportes para impresión por papel.

**Comment by willymarpuk** [comment]
Se agregaron los reportes en PDF y XLS

**Comment by ahalaburda** [comment]
*-faltan agregar un modal en departamentos para agregar un país si es necesario y en ciudades un modal de departamento.

**Comment by ahalaburda** [comment]
Se agrego modal en departamento y ciudades, con la funcionalidad de búsqueda filtrada
