### ISSUE TITLE
Log de Auditoria

### ISSUE THREAD

**Issue by willymarpuk** [ahalaburda/gestion#65]
Agregar la tabla Auditorias al modelo de  datos, y cargar datos a la misma mediante procedimientos almacenados y triggers. Hacer una vista para mostrar el log an la aplicacion en desarrollo y agregar funcionalidad de reportes para el mismo.

**Comment by willymarpuk** [comment]
Se agrego la tabla Auditorias a la base de datos pero aun no se actualizo el modelo de datos, se realizaron los triggers y el procedimiento almacenado para la carga de datos para la tabla Auditorias. Se realizo la vista para el log de auditoria y la funcionalidad de reportes.

**Comment by willymarpuk** [comment]
Se agrego la tabla Auditorias al modelo de datos, falta que se muestre el nombre de usuario que realiza cada acción.

**Comment by ahalaburda** [comment]
Se realizaron pruebas con callback desde la aplicación pero no tuvimos los resultados esperados para obtener el usuario actual.

**Comment by willymarpuk** [comment]
Se agrego la gema audited-activerecord para poder solucionar el problema de usuarios en auditoria, se creo una nueva tabla para el mismo.
Faltantes:
- Reportes

**Comment by willymarpuk** [comment]
Se realizaron los reportes para auditoria
