### ISSUE TITLE
Tabla de parametros

### ISSUE THREAD

**Issue by willymarpuk** [ahalaburda/gestion#78]

**Comment by willymarpuk** [comment]
Se creo la tabla de parametros con la herramienta scaffold, falta mejorar su interfaz

**Comment by ahalaburda** [comment]
Se mejoro la interfaz de la UI de parametros

**Comment by willymarpuk** [comment]
Se agrego la gema carrierwave para poder trabajar con imagenes, mediante el mismo podemos agregar el logo de la empresa. Como otro parametro podemos modificar el nombre de la empresa.
